project:
  name: Hotspot Batch
  version: 1.0.0

batch:
  log-aggregation:
    scheduler:
      enabled: true
      keep-alive: true
      initial-delay-ms: 5000
      fixed-delay-ms: 2000

spring:
  application:
    name: batch

  main:
    web-application-type: none

  batch:
    job:
      enabled: false

  profiles:
    default: local

  config:
    import:
      - classpath:postgres-batch.yml
      - classpath:redis.yml
      - classpath:postgres-main.yml
      - classpath:resilience4j.yml
      - classpath:llm-config.yml

---
spring:
  config:
    activate:
      on-profile: local

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: dev

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO
