project:
  name: Hotspot Batch
  version: 1.0.0

spring:
  application:
    name: batch

  main:
    web-application-type: none

  batch:
    job:
      enabled: false

  profiles:
    default: local

  config:
    import:
      - classpath:postgres.yml
      - classpath:redis.yml
      - classpath:postgres-main.yml

---
spring:
  config:
    activate:
      on-profile: local

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: dev

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO
